apiVersion: v1
data:
  default.toml: |-
    [k8s]
    addr = ""
    token = ""
    namespace = "default"
    [db]
    dsn = "root:root@tcp(webook-mysql:11308)/webook"
    [redis]
    addr = "webook-redis:6379"
kind: ConfigMap
metadata:
  name: webook
  namespace: default
