apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook
spec:
  # 副本数量
  replicas: 1
  selector:
    matchLabels:
      app: webook
  # template 描述的是pod是怎样的
  template:
    metadata:
      name: webook
      labels:
        app: webook
    # pod 的基本信息
    spec:
      containers:
        - name: webook
          image: ting17/webook:v0.0.4
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /data/config
              name: config-volume-webook
      volumes:
        - name: config-volume-webook
          projected:
            defaultMode: 420
            sources:
              - configMap:
                  name: webook
